### ISSUE TITLE
GX5-25 && /nav/odom

### ISSUE THREAD

**Issue by isValid** [LORD-MicroStrain/microstrain_inertial#59]
I use the latest driver and GX5-25, how to get the position data of /nav/odom

**Comment by ianmoore95** [comment]
Hello isValid, 
The GX5-25 does not have GNSS position capability. If that is a desired output for your application, I recommend the GX5-45 or GQ7. The GX5-45 offers a smaller form-factor and provides 2m accuracy while the GQ7 is immune to magnetic interference and provides 2cm accuracy. microstrain.com/inertial-sensors/3DM-GX5-45, microstrain.com/inertial-sensors/3dm-gq7

**Comment by robbiefish** [comment]
Closing this as it appears to be solved. Please feel free to reopen if you still need help
