### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by Aposhian** [LORD-MicroStrain/microstrain_inertial#63]
I would love to see a ROS2 version of this driver. Given that most of the heavy lifting seems to be done by the C++ library, hopefully this wouldn't require too much effort.

**Comment by nathanmillerparker** [comment]
We are working on a ROS 2 version... stay tuned.

**Comment by nathanmillerparker** [comment]
A beta version of this is available at https://github.com/LORD-MicroStrain/ROS2_MSCL

**Comment by robbiefish** [comment]
Full ROS2 support has been added in the [ros2](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros2) branch.

I am closing this issue as the support has now been added. Please feel free to open a new issue if you have other questions or issues with the ROS2 driver
