### ISSUE TITLE
GQ7 Delta-Theta and Delta-Velocity Outputs in ROS Driver

### ISSUE THREAD

**Issue by JTomasi** [LORD-MicroStrain/microstrain_inertial#66]
Hello,

Is it possible to obtain the delta-theta and delta-velocity measurements using the ROS driver for the 3DM-GQ7? I noticed that the manual for this device states that these values are expressed in the sensor frame, so I am assuming that they can be obtained using SensorConnect. Can they be obtained using the ROS driver? Is there a parameter that needs to be updated in the configuration/launch file so that these values are output by the ROS driver? 

Thanks,
Justin

**Comment by nathanmillerparker** [comment]
Sorry for the delay... these are not output by the driver as of right now.  They can be obtained by the driver, but it would require modification of code.
