### ISSUE TITLE
GitHub Link for MSCL missing or corrupted

### ISSUE THREAD

**Issue by snowflakeHG** [LORD-MicroStrain/microstrain_inertial#67]
The link posted back on Google
https://github.com/LORD-MicroStrain/ROS-MSCL/blob/master/CMakeLists.txt
is not anymore existing.
Is there any CMake configuration we could use to integrate any SW with your C++ MSCL code (RTK included) ?

**Comment by nathanmillerparker** [comment]
Are you using ROS?  If so, you can just download or checkout the code.  It contains the cmakelist.  I'll update the link to point to this file: https://github.com/LORD-MicroStrain/ROS-MSCL/blob/master/ros_mscl/CMakeLists.txt

**Comment by robbiefish** [comment]
Closing this as it appears to be solved. Please reopen this issue if it is still not working
